### ISSUE TITLE
อยากให้ตายไม่เสีย XP ครับ

### ISSUE THREAD

**Issue by MossXDDDDD** [Speedspencer/MashedPotato#4]

**Comment by Speedspencer** [comment]
Rank Immortal ไม่เสียคับผม แต่Xp ที่เสียจะลดลงไปเรื่อยๆตามแรงค์ที่ขึ้นครับ

**Comment by MossXDDDDD** [comment]
อ่อออ คับ


ในวันที่ อ. 29 ธ.ค. 2020 เวลา 12:57 _Yusaki <notifications@github.com>
เขียนว่า:
